// data/*.json → src/generated/data.ts
// Embeds the JSON as a JSON.parse'd string: works in every bundler and in Node (no JSON import, no import
// attributes), and JSON.parse is faster than parsing a large object literal.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const read = (f) => JSON.stringify(JSON.parse(readFileSync(new URL(`../data/${f}`, import.meta.url), "utf8")));
mkdirSync(new URL("../src/generated/", import.meta.url), { recursive: true });
writeFileSync(
  new URL("../src/generated/data.ts", import.meta.url),
  `// Generated by scripts/gen-data.mjs — do not edit. Source: data/country.json, data/usa.json\n` +
    `import type { Country, UsaState } from "../types.js";\n` +
    `export const countries: Country[] = JSON.parse(${JSON.stringify(read("country.json"))});\n` +
    `export const usaStates: UsaState[] = JSON.parse(${JSON.stringify(read("usa.json"))});\n`
);
console.log("generated src/generated/data.ts");
